name: Update gist with WakaTime stats
on:
  schedule:
    - cron:  '*/2 * * * *'
  workflow_dispatch:    
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: cddc621f2309143889387df2139d339e
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
